services:
  postgres:
    image: postgres
    container_name: do-it-now-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
    # - /var/lib/postgresql
    - ./docker-init/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    tmpfs:
      - /var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devnet

  backend:
    build: ./backend
    container_name: do-it-now-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      DO_IT_NOW_DB_USERNAME: postgres
      DO_IT_NOW_DB_PASSWORD: postgres
      SPRING_LIQUIBASE_ENABLED: "true"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - devnet

# volumes:
#   postgres_data:

networks:
  devnet:
    driver: bridge